-- MySQL Script generated by MySQL Workbench
-- 03/26/15 10:38:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserAccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `userID` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `securityQuestion` VARCHAR(45) NOT NULL,
  `securityAnswer` VARCHAR(45) NOT NULL,
  `accountReason` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `accountApproval` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documentName` VARCHAR(45) NULL,
  `documentLink` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `student_id` INT NOT NULL,
  `courseNumber` VARCHAR(15) NULL,
  `liveLink` TEXT NULL,
  `abstract` TEXT NULL,
  `screencastLink` TEXT NULL,
  `semester` VARCHAR(20) NULL,
  `dateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `highlighted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `student_project_idx` (`student_id` ASC),
  CONSTRAINT `student_project`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`UserAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keyword` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`keyword`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectKeywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectKeywords` (
  `keyword_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`keyword_id`, `project_id`),
  INDEX `fk_Keyword_has_Project_Project1_idx` (`project_id` ASC),
  INDEX `fk_Keyword_has_Project_Keyword1_idx` (`keyword_id` ASC),
  CONSTRAINT `fk_Keyword_has_Project_Keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `mydb`.`Keyword` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Keyword_has_Project_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Committee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Committee` (
  `commitee_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `committeeEmail` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`, `committeeEmail`),
  INDEX `fk_Project_has_UserAccount_Project1_idx` (`project_id` ASC),
  UNIQUE INDEX `commitee_id_UNIQUE` (`commitee_id` ASC),
  CONSTRAINT `fk_Project_has_UserAccount_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectStatistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectStatistics` (
  `project_id` INT NOT NULL,
  `views` INT NULL,
  `downloads` INT NULL,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `fk_project_statistics`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subscribers` (
  `keyword_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  INDEX `fk_Subscribers_Keyword1_idx` (`keyword_id` ASC),
  PRIMARY KEY (`keyword_id`, `email`),
  CONSTRAINT `fk_Subscribers_Keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `mydb`.`Keyword` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectSubmissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectSubmissions` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `document_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `approved` TINYINT(1) NULL,
  `dateSubmitted` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`, `document_id`),
  INDEX `fk_sub_document_idx` (`document_id` ASC),
  UNIQUE INDEX `submission_id_UNIQUE` (`submission_id` ASC),
  CONSTRAINT `fk_sub_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`Documents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Approval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Approval` (
  `submission_id` INT NOT NULL,
  `committee_id` INT NOT NULL,
  `approved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`submission_id`, `committee_id`),
  INDEX `fk_ProjectSubmissions_has_Committee_Committee1_idx` (`submission_id` ASC, `committee_id` ASC),
  CONSTRAINT `fk_ProjectSubmissions_has_Committee_ProjectSubmissions1`
    FOREIGN KEY (`submission_id`)
    REFERENCES `mydb`.`ProjectSubmissions` (`submission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectSubmissions_has_Committee_Committee1`
    FOREIGN KEY (`submission_id` , `committee_id`)
    REFERENCES `mydb`.`Committee` (`project_id` , `commitee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
